#!/bin/sh -f

\rm results.csv
\rm ovhd_dl_max.csv
\rm ovhd_dl_total.csv
\rm ovhd_al_max.csv
\rm ovhd_al_total.csv

#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > results.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_dl_max.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_dl_total.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_al_max.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_al_total.csv

./DataGenerator 4 

I=65
while  [ $I -ne 100 ]
do
	I=`expr $I + 5`
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "******** Periodic Tasks: $I % ********" >> results.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_dl_max.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_dl_total.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_al_max.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_al_total.csv
	

	echo "******** $I % $X data ********" >> run.txt
	cp -p ./periodic.cfg.${I}-1 ./periodic1.cfg &
	cp -p ./periodic.cfg.${I}-2 ./periodic2.cfg &
	cp -p ./periodic.cfg.${I}-3 ./periodic3.cfg &
	cp -p ./periodic.cfg.${I}-4 ./periodic4.cfg &
	cp -p ./periodic.cfg.${I}-5 ./periodic5.cfg &
	cp -p ./periodic.cfg.${I}-6 ./periodic6.cfg &
	cp -p ./periodic.cfg.${I}-7 ./periodic7.cfg &
	cp -p ./periodic.cfg.${I}-8 ./periodic8.cfg &
	cp -p ./periodic.cfg.${I}-9 ./periodic9.cfg &
	cp -p ./periodic.cfg.${I}-10 ./periodic10.cfg
	wait
	./Schedule ./periodic1.cfg >> results1.csv 
	./Schedule ./periodic2.cfg >> results2.csv 
	./Schedule ./periodic3.cfg >> results3.csv 
	./Schedule ./periodic4.cfg >> results4.csv 
	./Schedule ./periodic5.cfg >> results5.csv 
	./Schedule ./periodic6.cfg >> results6.csv 
	./Schedule ./periodic7.cfg >> results7.csv 
	./Schedule ./periodic8.cfg >> results8.csv 
	./Schedule ./periodic9.cfg >> results9.csv 
	./Schedule ./periodic10.cfg >> results10.csv
	wait
	
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> results.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_dl_max.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_dl_total.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_al_max.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_al_total.csv


	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> results.csv


	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_dl_max.csv

	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_dl_total.csv

	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_al_max.csv

	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_al_total.csv
done

python mail.py results.csv
