#!/bin/sh -f

UAP_TASK_SET=TS-5

\rm results.csv
\rm ovhd_dl_max.csv
\rm ovhd_dl_total.csv
\rm ovhd_al_max.csv
\rm ovhd_al_total.csv

#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > results.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_dl_max.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_dl_total.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_al_max.csv
#echo ",RM, TBS, TBS+VRA, ATBS, ATBS+VRA, TB*/TB(n), CBS" > ovhd_al_total.csv

./DataGenerator 4 

I=65
while  [ $I -ne 95 ]
do
	I=`expr $I + 5`
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "" >> results.csv
	echo "" >> ovhd_dl_max.csv
	echo "" >> ovhd_dl_total.csv
	echo "" >> ovhd_al_max.csv
	echo "" >> ovhd_al_total.csv
	echo "******** Periodic Tasks: $I % ********" >> results.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_dl_max.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_dl_total.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_al_max.csv
	echo "******** Periodic Tasks: $I % ********" >> ovhd_al_total.csv
	

	X=0
	while  [ $X -ne 10 ]
	do
		X=`expr $X + 1`
		echo "******** $I % $X data ********" >> run.txt
		cp -p ./periodic.cfg.${I}-${X} ./periodic.cfg
		./Schedule >> results.csv
	done
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> results.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_dl_max.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_dl_total.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_al_max.csv
	echo "Average,=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0]),=AVERAGE(R[-10]C[0]:R[-1]C[0])" >> ovhd_al_total.csv


	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> results.csv


	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_dl_max.csv

	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_dl_total.csv

	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_al_max.csv

	echo "$I%,\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\",\"=AVERAGE(R[-1]C,R[-15]C,R[-29]C,R[-43]C,R[-57]C,R[-71]C,R[-85]C,R[-99]C,R[-113]C,R[-127]C)\"" >> ovhd_al_total.csv
done

python mail.py results.csv